- hosts:
    - redirectors
  remote_user: ansible
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: push nginx config
      copy:
        src: nginx.conf
        dest: /etc/nginx/conf.d/servicesourcing.conf
        owner: root
        group: root
        mode: 0644
    - name: restart nginx
      systemd:
        state: reloaded
        name: nginx